In [9]:
#!pip install nibabel
%matplotlib notebook
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
#plt.rcParams.update(params)
import h5py
import random
from tqdm.notebook import tqdm
import nibabel as nib
from glob import glob
from scipy.stats import ks_2samp

In [26]:
BASEPATH = ""

f = h5py.File(f'{BASEPATH}10003.mat','r')

f.keys()

data = f['SM_feature']
array = data[()]


"""
f, ax = plt.subplots(1,4)
#f.set_size_inches(25, 10)
for i in range(4):
    ax[i].imshow(array[i*5, :, 10, :])    #cmap ="gray"
plt.show()
"""

print(array.shape)
print(array[1*5, :, 10, :])
print(array[1].shape)

(53, 52, 63, 53)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(52, 63, 53)
